[2024-04-16T18:04:27.248+0000] {processor.py:161} INFO - Started process (PID=28939) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:04:27.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:04:27.250+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:04:27.249+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:04:27.256+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:04:27.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:04:27.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:04:27.268+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.022 seconds
[2024-04-16T18:04:57.758+0000] {processor.py:161} INFO - Started process (PID=28950) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:04:57.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:04:57.761+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:04:57.761+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:04:57.768+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:04:57.766+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:04:57.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:04:57.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.031 seconds
[2024-04-16T18:05:28.196+0000] {processor.py:161} INFO - Started process (PID=28961) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:05:28.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:05:28.197+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:05:28.197+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:05:28.200+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:05:28.200+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:05:28.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:05:28.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.016 seconds
[2024-04-16T18:05:58.645+0000] {processor.py:161} INFO - Started process (PID=28972) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:05:58.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:05:58.649+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:05:58.649+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:05:58.655+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:05:58.654+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:05:58.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:05:58.671+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.030 seconds
[2024-04-16T18:06:29.092+0000] {processor.py:161} INFO - Started process (PID=28983) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:06:29.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:06:29.096+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:06:29.095+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:06:29.102+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:06:29.100+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:06:29.103+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:06:29.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.032 seconds
[2024-04-16T18:06:59.584+0000] {processor.py:161} INFO - Started process (PID=28994) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:06:59.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:06:59.588+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:06:59.587+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:06:59.594+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:06:59.592+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:06:59.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:06:59.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.031 seconds
[2024-04-16T18:07:30.066+0000] {processor.py:161} INFO - Started process (PID=29004) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:07:30.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:07:30.069+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:07:30.069+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:07:30.075+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:07:30.073+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:07:30.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:07:30.091+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.029 seconds
[2024-04-16T18:08:00.528+0000] {processor.py:161} INFO - Started process (PID=29015) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:08:00.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:08:00.532+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:08:00.531+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:08:00.538+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:08:00.537+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:08:00.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:08:00.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.038 seconds
[2024-04-16T18:08:30.967+0000] {processor.py:161} INFO - Started process (PID=29026) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:08:30.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:08:30.969+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:08:30.969+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:08:30.975+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:08:30.973+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:08:30.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:08:30.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.026 seconds
[2024-04-16T18:09:01.489+0000] {processor.py:161} INFO - Started process (PID=29037) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:09:01.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:09:01.493+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:09:01.492+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:09:01.499+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:09:01.497+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:09:01.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:09:01.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.033 seconds
[2024-04-16T18:09:31.998+0000] {processor.py:161} INFO - Started process (PID=29048) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:09:32.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:09:32.001+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:09:32.001+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:09:32.007+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:09:32.006+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:09:32.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:09:32.025+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.031 seconds
[2024-04-16T18:10:02.525+0000] {processor.py:161} INFO - Started process (PID=29059) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:10:02.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:10:02.528+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:10:02.528+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:10:02.532+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:10:02.531+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:10:02.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:10:02.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.026 seconds
[2024-04-16T18:10:33.057+0000] {processor.py:161} INFO - Started process (PID=29070) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:10:33.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:10:33.060+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:10:33.060+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:10:33.065+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:10:33.064+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:10:33.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:10:33.080+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.026 seconds
[2024-04-16T18:11:03.522+0000] {processor.py:161} INFO - Started process (PID=29081) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:11:03.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:11:03.527+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:11:03.526+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:11:03.532+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:11:03.531+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:11:03.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:11:03.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.030 seconds
[2024-04-16T18:11:34.215+0000] {processor.py:161} INFO - Started process (PID=29092) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:11:34.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:11:34.218+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:11:34.218+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:11:34.224+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:11:34.221+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:11:34.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:11:34.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.027 seconds
[2024-04-16T18:12:04.725+0000] {processor.py:161} INFO - Started process (PID=29103) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:12:04.727+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:12:04.728+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:12:04.728+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:12:04.735+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:12:04.733+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:12:04.736+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:12:04.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.033 seconds
[2024-04-16T18:12:35.287+0000] {processor.py:161} INFO - Started process (PID=29113) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:12:35.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:12:35.291+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:12:35.290+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:12:35.296+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:12:35.295+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:12:35.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:12:35.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.030 seconds
[2024-04-16T18:13:05.777+0000] {processor.py:161} INFO - Started process (PID=29124) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:13:05.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:13:05.781+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:13:05.780+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:13:05.787+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:13:05.785+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:13:05.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:13:05.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.031 seconds
[2024-04-16T18:13:36.271+0000] {processor.py:161} INFO - Started process (PID=29135) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:13:36.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:13:36.274+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:13:36.273+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:13:36.279+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:13:36.278+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:13:36.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:13:36.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.026 seconds
[2024-04-16T18:14:06.777+0000] {processor.py:161} INFO - Started process (PID=29146) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:14:06.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:14:06.780+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:14:06.780+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:14:06.786+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:14:06.784+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:14:06.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:14:06.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.031 seconds
[2024-04-16T18:14:37.310+0000] {processor.py:161} INFO - Started process (PID=29157) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:14:37.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:14:37.314+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:14:37.313+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:14:37.320+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:14:37.318+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:14:37.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:14:37.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.033 seconds
[2024-04-16T18:15:07.784+0000] {processor.py:161} INFO - Started process (PID=29168) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:15:07.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:15:07.786+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:15:07.786+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:15:07.793+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:15:07.791+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:15:07.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:15:07.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.030 seconds
[2024-04-16T18:15:38.346+0000] {processor.py:161} INFO - Started process (PID=29178) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:15:38.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:15:38.349+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:15:38.349+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:15:38.355+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:15:38.353+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:15:38.355+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:15:38.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.030 seconds
[2024-04-16T18:16:08.859+0000] {processor.py:161} INFO - Started process (PID=29189) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:16:08.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:16:08.862+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:16:08.862+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:16:08.869+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:16:08.867+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:16:08.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:16:08.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.032 seconds
[2024-04-16T18:16:39.324+0000] {processor.py:161} INFO - Started process (PID=29200) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:16:39.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:16:39.326+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:16:39.326+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:16:39.332+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:16:39.330+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:16:39.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:16:39.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.030 seconds
[2024-04-16T18:17:09.781+0000] {processor.py:161} INFO - Started process (PID=29211) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:17:09.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:17:09.784+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:17:09.783+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:17:09.789+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:17:09.788+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:17:09.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:17:09.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.029 seconds
[2024-04-16T18:17:40.266+0000] {processor.py:161} INFO - Started process (PID=29222) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:17:40.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:17:40.268+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:17:40.267+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:17:40.273+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:17:40.271+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:17:40.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:17:40.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.024 seconds
[2024-04-16T18:18:10.796+0000] {processor.py:161} INFO - Started process (PID=29233) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:18:10.799+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:18:10.800+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:18:10.799+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:18:10.805+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:18:10.804+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:18:10.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:18:10.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.028 seconds
[2024-04-16T18:18:41.398+0000] {processor.py:161} INFO - Started process (PID=29244) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:18:41.399+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:18:41.400+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:18:41.400+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:18:41.405+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:18:41.404+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:18:41.405+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:18:41.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.021 seconds
[2024-04-16T18:19:12.013+0000] {processor.py:161} INFO - Started process (PID=29255) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:19:12.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:19:12.015+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:19:12.015+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:19:12.020+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:19:12.018+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:19:12.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:19:12.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.028 seconds
[2024-04-16T18:19:42.928+0000] {processor.py:161} INFO - Started process (PID=29266) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T18:19:42.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T18:19:42.930+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:19:42.930+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T18:19:42.935+0000] {logging_mixin.py:188} INFO - [2024-04-16T18:19:42.934+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T18:19:42.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T18:19:42.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.024 seconds
[2024-04-16T21:20:55.223+0000] {processor.py:161} INFO - Started process (PID=29273) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T21:20:55.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T21:20:55.247+0000] {logging_mixin.py:188} INFO - [2024-04-16T21:20:55.246+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T21:20:55.288+0000] {logging_mixin.py:188} INFO - [2024-04-16T21:20:55.281+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T21:20:55.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T21:20:55.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.203 seconds
[2024-04-16T22:00:23.156+0000] {processor.py:161} INFO - Started process (PID=29284) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T22:00:23.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T22:00:23.164+0000] {logging_mixin.py:188} INFO - [2024-04-16T22:00:23.163+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T22:00:23.180+0000] {logging_mixin.py:188} INFO - [2024-04-16T22:00:23.177+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T22:00:23.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T22:00:23.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.094 seconds
[2024-04-16T22:32:25.817+0000] {processor.py:161} INFO - Started process (PID=29295) to work on /opt/airflow/dags/big_conn.py
[2024-04-16T22:32:25.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/big_conn.py for tasks to queue
[2024-04-16T22:32:25.828+0000] {logging_mixin.py:188} INFO - [2024-04-16T22:32:25.827+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/big_conn.py
[2024-04-16T22:32:25.849+0000] {logging_mixin.py:188} INFO - [2024-04-16T22:32:25.844+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/big_conn.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_conn.py", line 3, in <module>
    from airflow.operators.bigquery_operator import BigQueryOperator
ModuleNotFoundError: No module named 'airflow.operators.bigquery_operator'
[2024-04-16T22:32:25.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/big_conn.py
[2024-04-16T22:32:25.921+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/big_conn.py took 0.128 seconds
