[2024-04-14T02:43:51.486+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: token_refresher_50mins.get_simple_data manual__2024-04-14T02:43:49.581432+00:00 [queued]>
[2024-04-14T02:43:51.490+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: token_refresher_50mins.get_simple_data manual__2024-04-14T02:43:49.581432+00:00 [queued]>
[2024-04-14T02:43:51.490+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-14T02:43:51.495+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_simple_data> on 2024-04-14 02:43:49.581432+00:00
[2024-04-14T02:43:51.499+0000] {standard_task_runner.py:60} INFO - Started process 1160 to run task
[2024-04-14T02:43:51.501+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'token_refresher_50mins', 'get_simple_data', 'manual__2024-04-14T02:43:49.581432+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token.py', '--cfg-path', '/tmp/tmpnaus6bvu']
[2024-04-14T02:43:51.501+0000] {standard_task_runner.py:88} INFO - Job 186: Subtask get_simple_data
[2024-04-14T02:43:51.520+0000] {task_command.py:423} INFO - Running <TaskInstance: token_refresher_50mins.get_simple_data manual__2024-04-14T02:43:49.581432+00:00 [running]> on host 209a9ac884b0
[2024-04-14T02:43:51.546+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='token_refresher_50mins' AIRFLOW_CTX_TASK_ID='get_simple_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T02:43:49.581432+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T02:43:49.581432+00:00'
[2024-04-14T02:43:51.613+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/refresh_token.py", line 74, in get_simple_data
    entries = response.json()["entries"]
KeyError: 'entries'
[2024-04-14T02:43:51.617+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=token_refresher_50mins, task_id=get_simple_data, execution_date=20240414T024349, start_date=20240414T024351, end_date=20240414T024351
[2024-04-14T02:43:51.622+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 186 for task get_simple_data ('entries'; 1160)
[2024-04-14T02:43:51.639+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-14T02:43:51.647+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
