[2024-04-16T14:27:05.487+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_atomation.py.get_data manual__2024-04-16T14:27:03.499365+00:00 [queued]>
[2024-04-16T14:27:05.491+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_atomation.py.get_data manual__2024-04-16T14:27:03.499365+00:00 [queued]>
[2024-04-16T14:27:05.491+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-16T14:27:05.495+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data> on 2024-04-16 14:27:03.499365+00:00
[2024-04-16T14:27:05.498+0000] {standard_task_runner.py:60} INFO - Started process 21809 to run task
[2024-04-16T14:27:05.499+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_atomation.py', 'get_data', 'manual__2024-04-16T14:27:03.499365+00:00', '--job-id', '397', '--raw', '--subdir', 'DAGS_FOLDER/spotify_atomation.py', '--cfg-path', '/tmp/tmp0882ta7r']
[2024-04-16T14:27:05.500+0000] {standard_task_runner.py:88} INFO - Job 397: Subtask get_data
[2024-04-16T14:27:05.516+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_atomation.py.get_data manual__2024-04-16T14:27:03.499365+00:00 [running]> on host 209a9ac884b0
[2024-04-16T14:27:05.541+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_atomation.py' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T14:27:03.499365+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-16T14:27:03.499365+00:00'
[2024-04-16T14:27:05.547+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.9', 29092)]>: connecting to broker:29092 [('172.19.0.9', 29092) IPv4]
[2024-04-16T14:27:05.547+0000] {conn.py:1206} INFO - Probing node bootstrap-0 broker version
[2024-04-16T14:27:05.547+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.9', 29092)]>: Connection complete.
[2024-04-16T14:27:05.653+0000] {conn.py:1268} INFO - Broker version identified as 2.6.0
[2024-04-16T14:27:05.654+0000] {conn.py:1269} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-04-16T14:27:05.656+0000] {spotify_atomation.py:88} INFO - Using access_token:BQA9h4tekZYtWzEHeVUYAYyP1u0U_QTiVEaM7OiulQnHzpXfV0WNryLQLoBBsyqKdEXVw_NbfcOBnxspnfTdS6QY_FOjZJl-jKpwm2PA3GGxiEtpG6eU5HcyvyRT7sJSjgkyW7r7kWL_N2_0bqzMbSa3AEqbJC0GLeTmK6uQIWd0LHT94-zN4zP4f2dT4vtq3vHI8ps0TJMbuLobBcvs5R6NSGaoyurpRl4N2hlEQnF220vA
[2024-04-16T14:27:05.656+0000] {spotify_atomation.py:90} INFO - Using url: https://charts-spotify-com-service.spotify.com/auth/v0/charts/regional-global-daily/2024-01-1
[2024-04-16T14:27:05.725+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_atomation.py", line 96, in get_data
    entries = response.json()["entries"]
KeyError: 'entries'
[2024-04-16T14:27:05.730+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_atomation.py, task_id=get_data, execution_date=20240416T142703, start_date=20240416T142705, end_date=20240416T142705
[2024-04-16T14:27:06.167+0000] {logging_mixin.py:188} INFO -  ⚠️️Task Run Failed!⚠️>>Check Task get_data
[2024-04-16T14:27:06.176+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 397 for task get_data ('entries'; 21809)
[2024-04-16T14:27:06.188+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-16T14:27:06.201+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
