[2024-04-14T01:51:50.330+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: token_refresher_50mins.refresh_token scheduled__2024-04-13T22:30:00+00:00 [queued]>
[2024-04-14T01:51:50.341+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: token_refresher_50mins.refresh_token scheduled__2024-04-13T22:30:00+00:00 [queued]>
[2024-04-14T01:51:50.342+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-14T01:51:50.358+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): refresh_token> on 2024-04-13 22:30:00+00:00
[2024-04-14T01:51:50.364+0000] {standard_task_runner.py:60} INFO - Started process 227 to run task
[2024-04-14T01:51:50.366+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'token_refresher_50mins', 'refresh_token', 'scheduled__2024-04-13T22:30:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token.py', '--cfg-path', '/tmp/tmpoltjjmdg']
[2024-04-14T01:51:50.369+0000] {standard_task_runner.py:88} INFO - Job 115: Subtask refresh_token
[2024-04-14T01:51:50.414+0000] {task_command.py:423} INFO - Running <TaskInstance: token_refresher_50mins.refresh_token scheduled__2024-04-13T22:30:00+00:00 [running]> on host 209a9ac884b0
[2024-04-14T01:51:50.462+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='token_refresher_50mins' AIRFLOW_CTX_TASK_ID='refresh_token' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T22:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-13T22:30:00+00:00'
[2024-04-14T01:51:50.463+0000] {oauth2.py:471} INFO - User authentication requires interaction with your web browser. Once you enter your credentials and give authorization, you will be redirected to a url.  Paste that url you were directed to to complete the authorization.
[2024-04-14T01:51:50.463+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/refresh_token.py", line 34, in refresh_token
    current_user = sp.current_user()
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 1227, in current_user
    return self.me()
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 1221, in me
    return self._get("me/")
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 323, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 247, in _internal_call
    headers = self._auth_headers()
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 238, in _auth_headers
    token = self.auth_manager.get_access_token(as_dict=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 535, in get_access_token
    "code": code or self.get_auth_response(),
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 490, in get_auth_response
    return self._get_auth_response_local_server(redirect_port)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 457, in _get_auth_response_local_server
    server = start_local_http_server(redirect_port)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 1303, in start_local_http_server
    server = HTTPServer(("127.0.0.1", port), handler)
  File "/usr/local/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.8/http/server.py", line 139, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
[2024-04-14T01:51:50.469+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=token_refresher_50mins, task_id=refresh_token, execution_date=20240413T223000, start_date=20240414T015150, end_date=20240414T015150
[2024-04-14T01:51:50.477+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 115 for task refresh_token ([Errno 98] Address already in use; 227)
[2024-04-14T01:51:50.507+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-14T01:51:50.519+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
